Create er diagram
mikurikuri1919/Todo-For-7Habits pull request #4
Opened 2023-10-06 06:19 UTC by mikurikuri1919

ER図を作成しました。
お手数ですが、ご確認お願い致します。

## ER図
[![Image from Gyazo](https://i.gyazo.com/3e509a56a9b5f4fa51ce6c947a0bedc0.png)](https://gyazo.com/3e509a56a9b5f4fa51ce6c947a0bedc0)

## 各テーブルについて
### Users
- Firebase AuthenticationのGoogle認証を使用します。
- Profileテーブルも作成した方が良いか悩みましたが、Usersテーブルで事足りると考えたため、こちらにプロフィール画面で設定するavatar, twitter_usernameなどのカラムを持たせました。
- 管理者画面を作るために、roleカラムを作成しました。

### Todos
- 各ユーザーが作成したToDo項目が格納されます。ToDoのID、ユーザーID（外部キー）、ToDoのタイトル、詳細、期限日、完了状態などの情報が含まれます。
- zoneカラムは、第1〜4領域を管理するための作成します。

### Default_todos
- 新規ユーザー登録時に、TodosテーブルにデフォルトのTodoを作成する実装方法でも良かったですが、こちらにデフォルトのTodoを格納しておく方がデータの構造として、綺麗かなと考えたので、作成します。
- due_dateとstatusは作成しません。

### Line_notifications
- LINE通知の設定情報を格納するためのテーブルです。このテーブルにはユーザーごとのLINE通知設定情報が格納されます。ユーザーID（外部キー）とLINE通知の設定情報（例: 通知の有効化、通知の頻度など）が含まれます。
- ユーザーがLINE通知のカスタマイズを行う際に使用されます。

### Recommendations
- このテーブルにはユーザーに対するレコメンド情報が格納されます。ユーザーID（外部キー）とレコメンドされたToDoなどが含まれます。特定のToDoをユーザーに提案するために使用されます。

### Achievement_rates
- ユーザーごとにToDoの達成率を計算し、それを記録および表示するためのテーブルです。達成率は通常、完了したToDoの数と全てのToDoの数の比率で表されます。

2023-10-06 10:34 UTC, tarakish requested changes
確認しました👍
お手数ですが、各カラムについてはデータ型も一緒に記載していただけますでしょうか？
enumを利用する場合はどういう値が入るかのご説明も合わせていただけるとレビューしやすくなるのでお願いします！

2023-10-07 05:00 UTC, mikurikuri1919 commented
ER図に各カラムのデータ型を追加しました。
また、enumを使用するカラムの詳細情報について、ER図の下に記載しました。
お手数ですが、ご確認お願い致します。

## ER図
[![Image from Gyazo](https://i.gyazo.com/680c71daf94ef51b16b25d22856cfbf6.png)](https://gyazo.com/680c71daf94ef51b16b25d22856cfbf6)

## enumを使用するカラムについて
### role
- general : 1
- admin : 2

### status
- not_complete : 1
- complete : 2

### zone
- first_zone : 1
- second_zone : 2
- third_zone : 3
- fourth_zone : 4

2023-10-07 06:28 UTC, tmtkzk0823 commented
修正ありがとうございます。

私からもコメントさせていただきますね。
- 全体
  - テーブル名はスネークケースでの記載をお願いします。

- データ型と同じく各カラムがどのような値を持つかプルリクエストのコメント欄に記載していただいてもよろしいでしょうか？

- default_todosテーブルは、こちらにデフォルトのTodoを格納しておくテーブルだと思いますが、レコードはいくつぐらいになることを想定していますでしょうか？（新規登録後のデータなので1つしか無い？）

2023-10-07 07:09 UTC, mikurikuri1919 commented
レビューいただき、ありがとうございます。
ご指摘いただいた3点について、以下のように対応しました。
お手数ですが、再度ご確認をお願い致します。

- テーブル名はスネークケースでの記載をお願いします。
	- ER図を修正済み
- データ型と同じく各カラムがどのような値を持つかプルリクエストのコメント欄に記載していただいてもよろしいでしょうか？
	- ER図の下に記載
- default_todosテーブルは、こちらにデフォルトのTodoを格納しておくテーブルだと思いますが、レコードはいくつぐらいになることを想定していますでしょうか？（新規登録後のデータなので1つしか無い？）
  - 各領域につき、1つか2つのデフォルトTodoを想定しています。なので多くてレコード数は8つほどだと思います。こちら少し悩んだのですが、あまりデータ数が多くないのであれば、Todosテーブルのみ作成して、新規登録時にいくつかデフォルトでTodoを作成するという設計の方がよろしいでしょうか？すみませんが、助言いただけますと幸いです。

## ER図
[![Image from Gyazo](https://i.gyazo.com/412acd3a86ccc29d4ac9e1111f49fecd.png)](https://gyazo.com/412acd3a86ccc29d4ac9e1111f49fecd)

- users
	- user_id: ユーザーを一意に識別するためのユーザーIDです。
  - username: ユーザー名や表示名です。アプリ内で表示される名前です。
	- uid: Firebase Authenticationで生成されたユーザーの一意の識別子です。
	- role: ユーザーの役割を示すカラムで、一般ユーザーと管理者が含まれます。
	- avatar: プロフィール画面で設定します。ユーザーのプロフィール画像へのリンクやファイルパスです。ユーザーのアバターを表示するのに使用されます。
	- twitter_username: プロフィール画面で設定します。ユーザーがTwitterアカウントを持っている場合、そのユーザー名を格納します。

- todos
	- todo_id: ToDo項目を一意に識別するためのIDです。
	- user_id: ToDoを作成したユーザーを識別するための外部キーです。
	- title: ToDo項目のタイトルや名前です。
	- description: ToDo項目の詳細な説明やメモを格納するカラムです。
	- due_date: ToDoの期限日を示すカラムで、タスクの完了が期待される日付です。
	- status: ToDo項目の完了状態を示すカラムで、未完了と完了が含まれます。
	- zone: ToDo項目が所属する第1~4領域を識別するためのカラムです。第1領域、第2領域、第3領域、第3領域が含まれます。

- default_todos
	- default_todo_id: デフォルトのToDo項目を一意に識別するためのIDです。
	- user_id: デフォルトToDoを作成したユーザーを識別するための外部キーです。
	- title: デフォルトToDo項目のタイトルや名前です。新しいユーザーに提供されるデフォルトのToDoを定義します。
	- description: デフォルトToDo項目の詳細な説明やメモを格納するカラムです。
	- zone: ToDo項目が所属する第1~4領域を識別するためのカラムです。第1領域、第2領域、第3領域、第3領域が含まれます。

- line_notifications
	- line_notification_id: LINE通知設定情報を一意に識別するためのIDです。
	- user_id: LINE通知設定を行ったユーザーを識別するための外部キーです。
	- notification_settings: LINE通知の設定情報を格納するカラムで、通知の日付などを想定しています。
	- active: LINE通知が有効か無効かを示すフラグです。

- recommendations
	- recommendation_id: レコメンド情報を一意に識別するためのIDです。
	- user_id: レコメンドされたToDoを受け取るユーザーを識別するための外部キーです。
	- recommended_todo: レコメンドされたToDo項目を識別するためのカラムです。ユーザーに対して提案するためのToDoを定義します。

- achievement_rates
	- achievement_rate_id: ユーザーのToDo達成率を一意に識別するためのIDです。
	- user_id: 達成率を計算するユーザーを識別するための外部キーです。
	- rate: ユーザーのToDo達成率を示すカラムで、完了したToDoの数と全てのToDoの数の比率を格納します。
	- calculation_date: 達成率を計算した日付を示すカラムです。達成率の履歴を記録するのに使用されます。

2023-10-07 08:50 UTC, tmtkzk0823 commented
> テーブル名はスネークケースでの記載をお願いします。
ER図を修正済み
データ型と同じく各カラムがどのような値を持つかプルリクエストのコメント欄に記載していただいてもよろしいでしょうか？
ER図の下に記載

上記修正ありがとうございます。

> 領域につき、1つか2つのデフォルトTodoを想定しています。なので多くてレコード数は8つほどだと思います。こちら少し悩んだのですが、あまりデータ数が多くないのであれば、Todosテーブルのみ作成して、新規登録時にいくつかデフォルトでTodoを作成するという設計の方がよろしいでしょうか？すみませんが、助言いただけますと幸いです。

レコードが１つの場合はそのような形でもいいかなと思ったのですが、複数ある+その後のデフォルトのTodoを変えるとなった時に、ユーザーが登録するTodo切り分けたがいいと思ったのでそのままで大丈夫だと思います。

追加でコメントさせていただきますね。

- 全体
  - PKの値が`テーブル名_id`になっています。こちらは**外部キーを表現**する際の記述の仕方になると思いますので適切な形に修正をお願いします。

-  achievement_ratesテーブル
  - こちらは達成率の計算をするたびにupdateがかかるイメージでしょうか？であれば`alculation_date`の値は`update_at`の値を活用すればいいと思うのですがいかがでしょうか？
  - また、rateの値ですが、todosテーブルの値を使って計算するロジックを書けば、こちらの値を出すことができそうですがいかがでしょうか？

2023-10-08 06:40 UTC, mikurikuri1919 commented
レビューいただき、ありがとうございます。
ご指摘いただいた点について、以下のように対応しました。
お手数ですが、再度ご確認をお願い致します。

- PKの値がテーブル名_idになっています。こちらは外部キーを表現する際の記述の仕方になると思いますので適切な形に修正をお願いします。
	- ER図を修正済み
- achievement_ratesテーブルについて
	- ご指摘いただいた通り、todosテーブルで必要な機能を実装できそうなので、削除しました。

ご指摘いただいた内容ではないですが、機能が若干少ない気がしたので、追加でカテゴリー機能を追加しようと思いました。詳細は以下です。なのでER図にcategoriesテーブルとtodo_categoriesを追加しました。
- カテゴリー機能について
	- Trelloのようなイメージで1つのTodoに複数のカテゴリーラベルを付けられるようにします。また、1つのカテゴリーラベルは複数のTodoに付けることが可能なので、多対多の関係をイメージしております。
	- ちなみに、ラベルをユーザーが作成するという機能は今のところ実装予定はございません。一旦は、デフォルトのラベルを用意しておき、ユーザーから任意で選んでいただくイメージです。

## ER図
[![Image from Gyazo](https://i.gyazo.com/49bbe22fc2eb98c9c04306560ab74ac6.png)](https://gyazo.com/49bbe22fc2eb98c9c04306560ab74ac6)

2023-10-08 07:18 UTC, murata0705 approved these changes
良いと思います 👍🏻 
次の課題に進みましょう。

2023-10-08 08:53 UTC, merged